# -*- coding: utf-8 -*-
"""sustainibility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157VUI-fjQT8e2_teYk200hp7q1uNnnek
"""

!pip install -q geopandas rasterio shapely kagglehub geemap
!pip install -q torch torchvision scikit-learn matplotlib seaborn tqdm

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import rasterio
from rasterio.transform import rowcol
from shapely.geometry import box, Point
from pathlib import Path
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.models as models
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

print("All imports successful")
print(f"PyTorch version: {torch.__version__}")
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {DEVICE}")

import kagglehub

path = kagglehub.dataset_download("rishabhsnip/earth-observation-delhi-airshed")
print("Path to dataset files:", path)

from pathlib import Path

DATA_DIR       = Path(path)
DELHI_NCR_SHP  = DATA_DIR / "delhi_ncr_region.geojson"
AIRSHED_SHP    = DATA_DIR / "delhi_airshed.geojson"
LAND_COVER_TIF = DATA_DIR / "worldcover_bbox_delhi_ncr_2021.tif"
RGB_DIR        = DATA_DIR / "rgb"

for p in [DELHI_NCR_SHP, AIRSHED_SHP, LAND_COVER_TIF, RGB_DIR]:
    status = "✅" if p.exists() else "❌ MISSING"
    print(f"{status}  {p.name}")

METRIC_CRS  = "EPSG:32644"
GEO_CRS     = "EPSG:4326"
GRID_SIZE_M = 60_000  # 60 km in metres

delhi_ncr = gpd.read_file(DELHI_NCR_SHP)
airshed   = gpd.read_file(AIRSHED_SHP)

delhi_ncr_m = delhi_ncr.to_crs(METRIC_CRS)
airshed_m   = airshed.to_crs(METRIC_CRS)

minx, miny, maxx, maxy = delhi_ncr_m.total_bounds

grid_cells = []
x = minx
while x < maxx:
    y = miny
    while y < maxy:
        grid_cells.append(box(x, y, x + GRID_SIZE_M, y + GRID_SIZE_M))
        y += GRID_SIZE_M
    x += GRID_SIZE_M

grid_gdf = gpd.GeoDataFrame(geometry=grid_cells, crs=METRIC_CRS)
print(f"Total grid cells: {len(grid_gdf)}")

"""# **Spatial Reasoning & Data** **Filtering**"""

import geemap
import ee
ee.Authenticate()
ee.Initialize(project='srip-sustainibilty')

METRIC_CRS  = "EPSG:32644"
GEO_CRS     = "EPSG:4326"
GRID_SIZE_M = 60_000

delhi_ncr = gpd.read_file(DELHI_NCR_SHP)
airshed   = gpd.read_file(AIRSHED_SHP)

delhi_ncr_m = delhi_ncr.to_crs(METRIC_CRS)
airshed_m   = airshed.to_crs(METRIC_CRS)

minx, miny, maxx, maxy = delhi_ncr_m.total_bounds

grid_cells = []
x = minx
while x < maxx:
    y = miny
    while y < maxy:
        grid_cells.append(box(x, y, x + GRID_SIZE_M, y + GRID_SIZE_M))
        y += GRID_SIZE_M
    x += GRID_SIZE_M

grid_gdf = gpd.GeoDataFrame(geometry=grid_cells, crs=METRIC_CRS)
print(f"Total grid cells: {len(grid_gdf)}")

delhi_ncr_geo = delhi_ncr_m.to_crs(GEO_CRS)
airshed_geo   = airshed_m.to_crs(GEO_CRS)
grid_geo      = grid_gdf.to_crs(GEO_CRS)

# ── Plot on satellite basemap ──
Map = geemap.Map(center=[28.6, 77.2], zoom=8)
Map.add_basemap("SATELLITE")

Map.add_gdf(delhi_ncr_geo, layer_name="Delhi-NCR Region",
            style={"color": "cyan", "fillOpacity": 0.05, "weight": 2})

Map.add_gdf(airshed_geo,   layer_name="Delhi Airshed",
            style={"color": "red", "fillOpacity": 0.0, "weight": 2, "dashArray": "6 4"})

Map.add_gdf(grid_geo,      layer_name="60×60 km Grid",
            style={"color": "yellow", "fillOpacity": 0.0, "weight": 1})

Map.addLayerControl()
display(Map)

image_files = sorted(RGB_DIR.glob("*.png"))
print(f"Total images found: {len(image_files)}")

records = []
for f in image_files:
    try:
        parts = f.stem.split('_')
        lat, lon = float(parts[0]), float(parts[1])
        records.append({'filename': f.name, 'filepath': str(f), 'lat': lat, 'lon': lon})
    except Exception as e:
        print(f"⚠️ Could not parse: {f.name} — {e}")

images_df = pd.DataFrame(records)

geometry     = [Point(row['lon'], row['lat']) for _, row in images_df.iterrows()]
images_gdf   = gpd.GeoDataFrame(images_df, geometry=geometry, crs=GEO_CRS)
images_gdf_m = images_gdf.to_crs(METRIC_CRS)

images_inside = gpd.sjoin(images_gdf_m, delhi_ncr_m[['geometry']], how='inner', predicate='within')
images_inside = images_inside.drop(columns=['index_right']).reset_index(drop=True)

print(f"Images BEFORE filtering: {len(images_gdf)}")
print(f"Images AFTER  filtering: {len(images_inside)}")

print("=" * 45)
print(f"  Total images before filtering : {len(images_gdf):>5}")
print(f"  Total images after  filtering : {len(images_inside):>5}")
print("=" * 45)

# Convert to GEO_CRS for geemap
images_inside_geo = images_inside.to_crs(GEO_CRS)
images_outside    = images_gdf_m[~images_gdf_m['filename'].isin(images_inside['filename'])].to_crs(GEO_CRS)

Map2 = geemap.Map(center=[28.6, 77.2], zoom=8)
Map2.add_basemap("SATELLITE")

Map2.add_gdf(delhi_ncr_geo, layer_name="Delhi-NCR",
             style={"color": "cyan", "fillOpacity": 0.05, "weight": 2})

Map2.add_gdf(images_inside_geo, layer_name=f"Inside ({len(images_inside)})",
             style={"color": "lime", "fillOpacity": 1.0, "radius": 4, "weight": 0})

Map2.add_gdf(images_outside, layer_name=f"Outside ({len(images_outside)})",
             style={"color": "red", "fillOpacity": 0.6, "radius": 3, "weight": 0})

Map2.addLayerControl()
display(Map2)

"""# **Label Construction & Dataset Preparation**"""

ESA_CLASSES = {
    10: 'Tree Cover',    20: 'Shrubland',   30: 'Grassland',
    40: 'Cropland',      50: 'Built-up',    60: 'Bare/Sparse Vegetation',
    70: 'Snow and Ice',  80: 'Water Bodies',90: 'Herbaceous Wetland',
    95: 'Mangroves',    100: 'Moss and Lichen',
}

SIMPLIFIED_MAP = {
    10: 'Vegetation', 20: 'Vegetation', 30: 'Vegetation',
    40: 'Cropland',   50: 'Built-up',   60: 'Others',
    70: 'Others',     80: 'Water',      90: 'Others',
    95: 'Vegetation', 100: 'Others',
}

LABEL_TO_IDX = {'Vegetation': 0, 'Cropland': 1, 'Built-up': 2, 'Water': 3, 'Others': 4}
IDX_TO_LABEL = {v: k for k, v in LABEL_TO_IDX.items()}
PATCH_SIZE   = 128

print("Class mapping defined")

def extract_label_patch(lat, lon, tif_path, patch_size=128):
    with rasterio.open(tif_path) as src:
        row, col = rowcol(src.transform, lon, lat)
        half = patch_size // 2
        r0, r1 = row - half, row + half
        c0, c1 = col - half, col + half
        if r0 < 0 or c0 < 0 or r1 > src.height or c1 > src.width:
            return None
        window = rasterio.windows.Window(c0, r0, patch_size, patch_size)
        return src.read(1, window=window)

def get_dominant_class(patch):
    flat  = patch.flatten()
    valid = flat[flat > 0]
    if len(valid) == 0:
        return None
    values, counts = np.unique(valid, return_counts=True)
    return int(values[np.argmax(counts)])

from tqdm.notebook import tqdm

labeled_records = []
skipped = 0

for _, row in tqdm(images_inside.iterrows(), total=len(images_inside), desc="Labeling images"):
    patch = extract_label_patch(row['lat'], row['lon'], LAND_COVER_TIF, PATCH_SIZE)
    if patch is None:
        skipped += 1
        continue
    dominant_code = get_dominant_class(patch)
    if dominant_code is None:
        skipped += 1
        continue
    simplified_label = SIMPLIFIED_MAP.get(dominant_code, 'Others')
    labeled_records.append({
        'filename':      row['filename'],
        'filepath':      row['filepath'],
        'lat':           row['lat'],
        'lon':           row['lon'],
        'dominant_code': dominant_code,
        'esa_class':     ESA_CLASSES.get(dominant_code, 'Unknown'),
        'label':         simplified_label,
        'label_idx':     LABEL_TO_IDX[simplified_label],
    })

labeled_df = pd.DataFrame(labeled_records)
print(f"Labeled {len(labeled_df)} images  |  Skipped: {skipped}")
labeled_df.head()

COLORS = {
    'Vegetation': '#2ecc71', 'Cropland': '#f39c12',
    'Built-up':   '#e74c3c', 'Water':    '#3498db', 'Others': '#95a5a6'
}
all_labels = list(LABEL_TO_IDX.keys())

train_df, test_df = train_test_split(
    labeled_df, test_size=0.4, random_state=42, stratify=labeled_df['label']
)
train_df = train_df.reset_index(drop=True)
test_df  = test_df.reset_index(drop=True)

print(f"Train set: {len(train_df)} images ({len(train_df)/len(labeled_df)*100:.1f}%)")
print(f"Test  set: {len(test_df)} images ({len(test_df)/len(labeled_df)*100:.1f}%)")

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

for ax, df, title in zip(axes[:2], [train_df, test_df], ['Train Set (60%)', 'Test Set (40%)']):
    counts = df['label'].value_counts().reindex(all_labels, fill_value=0)
    bars   = ax.bar(counts.index, counts.values,
                    color=[COLORS[l] for l in counts.index], edgecolor='white', linewidth=1.2)
    ax.bar_label(bars, padding=3, fontsize=10)
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_ylabel('Number of Images')
    ax.set_ylim(0, counts.max() * 1.2)
    ax.grid(axis='y', linestyle=':', alpha=0.5)

full_counts = labeled_df['label'].value_counts().reindex(all_labels, fill_value=0)
axes[2].pie(full_counts.values,
            labels=full_counts.index,
            colors=[COLORS[l] for l in full_counts.index],
            autopct='%1.1f%%', startangle=140,
            wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})
axes[2].set_title('Full Dataset Distribution', fontsize=13, fontweight='bold')

plt.suptitle('Class Distribution Across Splits', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('/content/q2_class_dist.png', dpi=150, bbox_inches='tight')
plt.show()

"""# **Model Training & Supervised Evaluation**"""

class SentinelDataset(Dataset):
    def __init__(self, df, transform=None):
        self.df        = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row   = self.df.iloc[idx]
        image = Image.open(row['filepath']).convert('RGB')
        label = int(row['label_idx'])
        if self.transform:
            image = self.transform(image)
        return image, label

IMG_SIZE   = 128
BATCH_SIZE = 32

train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

train_dataset = SentinelDataset(train_df, transform=train_transform)
test_dataset  = SentinelDataset(test_df,  transform=test_transform)
train_loader  = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2, pin_memory=True)
test_loader   = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=True)

print(f"Train batches: {len(train_loader)}  |  Test batches: {len(test_loader)}")

NUM_CLASSES = len(LABEL_TO_IDX)

model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

# Freeze all layers except layer4 + fc (transfer learning)
for name, param in model.named_parameters():
    if 'layer4' not in name and 'fc' not in name:
        param.requires_grad = False

model.fc = nn.Sequential(
    nn.Dropout(0.4),
    nn.Linear(model.fc.in_features, NUM_CLASSES)
)
model = model.to(DEVICE)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total     = sum(p.numel() for p in model.parameters())
print(f"ResNet18 | Trainable params: {trainable:,} / {total:,} ({100*trainable/total:.1f}%)")

NUM_EPOCHS = 20
LR         = 1e-3

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LR, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=NUM_EPOCHS)

train_losses, test_losses = [], []
train_accs,   test_accs   = [], []

def evaluate(loader):
    model.eval()
    all_preds, all_labels, running_loss = [], [], 0.0
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs = model(images)
            running_loss += criterion(outputs, labels).item()
            all_preds.extend(outputs.argmax(dim=1).cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return running_loss / len(loader), accuracy_score(all_labels, all_preds), all_preds, all_labels

print("Starting training...")
for epoch in range(1, NUM_EPOCHS + 1):
    model.train()
    running_loss, correct, total_samples = 0.0, 0, 0

    for images, labels in train_loader:
        images, labels = images.to(DEVICE), labels.to(DEVICE)
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss  += loss.item()
        correct       += (outputs.argmax(dim=1) == labels).sum().item()
        total_samples += labels.size(0)

    scheduler.step()
    train_loss = running_loss / len(train_loader)
    train_acc  = correct / total_samples
    test_loss, test_acc, _, _ = evaluate(test_loader)

    train_losses.append(train_loss); test_losses.append(test_loss)
    train_accs.append(train_acc);    test_accs.append(test_acc)

    if epoch % 2 == 0 or epoch == 1:
        print(f"Epoch [{epoch:2d}/{NUM_EPOCHS}]  "
              f"Train Loss: {train_loss:.4f}  Acc: {train_acc:.4f}  |  "
              f"Test Loss: {test_loss:.4f}  Acc: {test_acc:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
epochs = range(1, NUM_EPOCHS + 1)

axes[0].plot(epochs, train_losses, 'b-o', markersize=4, label='Train Loss')
axes[0].plot(epochs, test_losses,  'r-s', markersize=4, label='Test Loss')
axes[0].set_title('Loss Curve', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')
axes[0].legend(); axes[0].grid(linestyle=':', alpha=0.5)

axes[1].plot(epochs, [a*100 for a in train_accs], 'b-o', markersize=4, label='Train Acc')
axes[1].plot(epochs, [a*100 for a in test_accs],  'r-s', markersize=4, label='Test Acc')
axes[1].set_title('Accuracy Curve', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy (%)')
axes[1].legend(); axes[1].grid(linestyle=':', alpha=0.5)

plt.suptitle('ResNet18 Training Curves', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/q3_training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

_, final_acc, final_preds, final_labels = evaluate(test_loader)

f1_macro    = f1_score(final_labels, final_preds, average='macro')
f1_weighted = f1_score(final_labels, final_preds, average='weighted')

print("=" * 50)
print(f"  Final Test Accuracy     : {final_acc*100:.2f}%")
print(f"  Macro F1-Score          : {f1_macro:.4f}")
print(f"  Weighted F1-Score       : {f1_weighted:.4f}")
print("=" * 50)

target_names = [IDX_TO_LABEL[i] for i in sorted(IDX_TO_LABEL.keys())]
print("\nDetailed Classification Report:")
print(classification_report(final_labels, final_preds, target_names=target_names))

cm      = confusion_matrix(final_labels, final_preds)
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)
class_names = [IDX_TO_LABEL[i] for i in sorted(IDX_TO_LABEL.keys())]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=class_names, yticklabels=class_names,
            linewidths=0.5, linecolor='lightgray')
axes[0].set_title('Confusion Matrix (Counts)', fontsize=13, fontweight='bold')
axes[0].set_ylabel('True Label'); axes[0].set_xlabel('Predicted Label')

sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='RdYlGn', ax=axes[1],
            xticklabels=class_names, yticklabels=class_names,
            vmin=0, vmax=1, linewidths=0.5, linecolor='lightgray')
axes[1].set_title('Confusion Matrix (Normalized)', fontsize=13, fontweight='bold')
axes[1].set_ylabel('True Label'); axes[1].set_xlabel('Predicted Label')

plt.suptitle('ResNet18 — Test Set Confusion Matrix', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/q3_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

test_df_copy = test_df.copy()
test_df_copy['pred_idx']   = final_preds
test_df_copy['pred_label'] = [IDX_TO_LABEL[p] for p in final_preds]

test_gdf_geo = gpd.GeoDataFrame(
    test_df_copy,
    geometry=[Point(r['lon'], r['lat']) for _, r in test_df_copy.iterrows()],
    crs=GEO_CRS
)

# GEE color map (geemap uses hex colors)
GEE_COLORS = {
    'Vegetation': '#2ecc71',
    'Cropland':   '#f39c12',
    'Built-up':   '#e74c3c',
    'Water':      '#3498db',
    'Others':     '#95a5a6',
}

# ── True Labels Map ──
Map3 = geemap.Map(center=[28.6, 77.2], zoom=9)
Map3.add_basemap("SATELLITE")
Map3.add_gdf(delhi_ncr_geo, layer_name="Delhi-NCR",
             style={"color": "white", "fillOpacity": 0.0, "weight": 2})

for lbl, color in GEE_COLORS.items():
    subset = test_gdf_geo[test_gdf_geo['label'] == lbl]
    if len(subset):
        Map3.add_gdf(subset, layer_name=f"True: {lbl}",
                     style={"color": color, "fillOpacity": 1.0, "radius": 5, "weight": 0})

Map3.addLayerControl()
print("── True Labels ──")
display(Map3)

# ── Predicted Labels Map ──
Map4 = geemap.Map(center=[28.6, 77.2], zoom=9)
Map4.add_basemap("SATELLITE")
Map4.add_gdf(delhi_ncr_geo, layer_name="Delhi-NCR",
             style={"color": "white", "fillOpacity": 0.0, "weight": 2})

for lbl, color in GEE_COLORS.items():
    subset = test_gdf_geo[test_gdf_geo['pred_label'] == lbl]
    if len(subset):
        Map4.add_gdf(subset, layer_name=f"Pred: {lbl}",
                     style={"color": color, "fillOpacity": 1.0, "radius": 5, "weight": 0})

Map4.addLayerControl()
print("── Predicted Labels ──")
display(Map4)

# ── Sample grid (keep matplotlib — showing actual image patches) ──
fig, axes = plt.subplots(3, 6, figsize=(18, 9))
sample_df = test_df_copy.sample(18, random_state=0)

for ax, (_, row) in zip(axes.flat, sample_df.iterrows()):
    img = Image.open(row['filepath']).convert('RGB')
    ax.imshow(img)
    correct = row['label_idx'] == row['pred_idx']
    color   = '#2ecc71' if correct else '#e74c3c'
    ax.set_title(f"GT: {row['label']}\nPred: {row['pred_label']}",
                 fontsize=8, color=color, fontweight='bold')
    ax.axis('off')
    for spine in ax.spines.values():
        spine.set_edgecolor(color); spine.set_linewidth(3)

plt.suptitle('Sample Predictions  (Green = Correct  |  Red = Wrong)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/sample_predictions.png', dpi=150, bbox_inches='tight')
plt.show()